# request
# cache
LIST_TABLE = 'LIST_TABLE'
RESET_CACHE = 'RESET_CACHE'

# table
DELETE = 'DELETE'
SET = 'SET'
GET = 'GET'
QUERY = 'QUERY'
DELETE_BATCH = 'DELETE_BATCH'
DELETE_ALL = 'DELETE_ALL'
SET_BATCH = 'SET_BATCH'
GET_BATCH = 'GET_BATCH'
RESET_TABLE = 'RESET_TABLE'
TABLE_SIZE = 'TABLE_SIZE'

# response
SUCCESS = 'SUCCESS'
ERROR = 'ERROR'
REP = 'REP'
REP_BATCH = 'REP_BATCH'
